package edu.wpi;

public enum QueryType {
    HASH_JOIN,
    NESTED_LOOP_JOIN,
    HASH_BASED_AGGREGATION_SUM_A,
    HASH_BASED_AGGREGATION_AVG_A,
    HASH_BASED_AGGREGATION_SUM_B,
    HASH_BASED_AGGREGATION_AVG_B
}
